/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;
import java.awt.Color;
import java.awt.Container;
import java.sql.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;



/**
 *
 * @author N AKSHAYA
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
        Container c=getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    public void getRecords(){
        try {
            Connection con=DBconnection.getConnection();
            PreparedStatement pst=con.prepareStatement("select * from fees_details order by reciept_no desc limit 1");
            ResultSet rs=pst.executeQuery();
            rs.next();
            txt_recieptNo.setText(rs.getString("reciept_no"));
            txt_paymentMode.setText(rs.getString("payment_mode"));
            String paymentMode=rs.getString("payment_mode");
            if(paymentMode.equalsIgnoreCase("cash")){
                lbl_chequeId.setText("Cheque Id");;
                txt_chequeId.setText("-");
                txt_bankName.setText("-");
            }
            if(paymentMode.equalsIgnoreCase("cheque")){
                lbl_chequeId.setText("Cheque Id");
                txt_chequeId.setText(rs.getString("cheque_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("dd")){
                lbl_chequeId.setText("DD");
                txt_chequeId.setText(rs.getString("dd_no"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("card")){
                lbl_chequeId.setText("Cheque Id");
                txt_chequeId.setText(rs.getString("-"));
                txt_bankName.setText(rs.getString("bank_name"));
            }
            txt_receviedName.setText(rs.getString("student_name"));
            txt_date.setText(rs.getString("date"));
            txt_year1.setText(rs.getString("year1"));
            txt_year2.setText(rs.getString("year2"));
            txt_gstin.setText(rs.getString("gstin"));
            txt_intialAmount.setText(rs.getString("amount"));
            txt_coursrName.setText(rs.getString("courses"));
            txt_cgst.setText(rs.getString("sgst"));
            txt_totalInwords.setText(rs.getString("total_in_words"));
            txt_total.setText(rs.getString("total_amount"));
            txt_remarks.setText(rs.getString("remark"));

            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        panelEditCourses = new javax.swing.JPanel();
        btnEditCourses = new javax.swing.JLabel();
        panelCourseList = new javax.swing.JPanel();
        btnCourseList = new javax.swing.JLabel();
        panelViewAllRecord = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelLogOut = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JLabel();
        panelPrint = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_paymentMode = new javax.swing.JLabel();
        txt_chequeId = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        txt_receviedName = new javax.swing.JLabel();
        txt_recieptNo = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_chequeId = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_coursrName = new javax.swing.JLabel();
        txt_cgst1 = new javax.swing.JLabel();
        txt_sgst2 = new javax.swing.JLabel();
        txt_intialAmount = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_cgst = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_remarks = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_totalInwords = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setPreferredSize(new java.awt.Dimension(350, 80));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHome.setPreferredSize(new java.awt.Dimension(350, 80));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("   Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        panelHome.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, -1));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 70));

        panelSearch.setBackground(new java.awt.Color(0, 102, 102));
        panelSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSearch.setPreferredSize(new java.awt.Dimension(350, 80));
        panelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSearch.setText("Search Record");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        panelSearch.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, -1));

        panelsideBar.add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 330, 70));

        panelEditCourses.setBackground(new java.awt.Color(0, 102, 102));
        panelEditCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEditCourses.setPreferredSize(new java.awt.Dimension(350, 80));
        panelEditCourses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditCourses.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnEditCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit.png"))); // NOI18N
        btnEditCourses.setText(" Edit Courses");
        btnEditCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCoursesMouseExited(evt);
            }
        });
        panelEditCourses.add(btnEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 50));

        panelsideBar.add(panelEditCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 330, 70));

        panelCourseList.setBackground(new java.awt.Color(0, 102, 102));
        panelCourseList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCourseList.setPreferredSize(new java.awt.Dimension(350, 80));
        panelCourseList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourseList.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnCourseList.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list_1.png"))); // NOI18N
        btnCourseList.setText("Course List");
        btnCourseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseListMouseExited(evt);
            }
        });
        panelCourseList.add(btnCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        panelsideBar.add(panelCourseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 330, 70));

        panelViewAllRecord.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelViewAllRecord.setPreferredSize(new java.awt.Dimension(350, 80));
        panelViewAllRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewAllRecord.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnViewAllRecord.setText("View All Record");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseExited(evt);
            }
        });
        panelViewAllRecord.add(btnViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, -1));

        panelsideBar.add(panelViewAllRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 330, 70));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBack.setPreferredSize(new java.awt.Dimension(350, 80));
        panelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/back1.png"))); // NOI18N
        btnBack.setText("     Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        panelBack.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, 70));

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 330, 70));

        panelLogOut.setBackground(new java.awt.Color(0, 102, 102));
        panelLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelLogOut.setPreferredSize(new java.awt.Dimension(350, 80));
        panelLogOut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });
        panelLogOut.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, -1));

        panelsideBar.add(panelLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 330, 70));

        panelPrint.setBackground(new java.awt.Color(0, 102, 102));
        panelPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPrint.setPreferredSize(new java.awt.Dimension(350, 80));
        panelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btnPrint.setText("  Print");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        panelPrint.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 290, -1));

        panelsideBar.add(panelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 330, 70));

        panelEdit.setBackground(new java.awt.Color(0, 102, 102));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEdit.setPreferredSize(new java.awt.Dimension(350, 80));
        panelEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit.png"))); // NOI18N
        btnEdit.setText(" Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        panelEdit.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 60));

        panelsideBar.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 1040));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/marri.jpg"))); // NOI18N
        panel_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 770, 160));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        panel_print.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1220, 6));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("The following payment in the collage office for  the year :");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 400, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("-");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 10, -1));

        txt_paymentMode.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_paymentMode.setText("Payment Mode:");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 150, -1));

        txt_chequeId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_chequeId.setText("Cheque Id:");
        panel_print.add(txt_chequeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 150, -1));

        txt_bankName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_bankName.setText("Bank Name:");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 150, -1));

        txt_receviedName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_receviedName.setText("Recevied Name:");
        panel_print.add(txt_receviedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 150, -1));

        txt_recieptNo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_recieptNo.setText("reciept no:");
        panel_print.add(txt_recieptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, -1));

        txt_year2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_year2.setText("2021");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 40, -1));

        txt_year1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_year1.setText("2021");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 40, -1));

        txt_gstin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_gstin.setText("GSTIN:");
        panel_print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 140, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Payment Mode:");
        panel_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 20));

        lbl_chequeId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_chequeId.setText("Cheque Id:");
        panel_print.add(lbl_chequeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Bank Name:");
        panel_print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 150, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Recevied Name:");
        panel_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 150, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Amount(rs):");
        panel_print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 90, 30));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_date.setText("Date:");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 130, -1));

        txt_sgst.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_sgst.setText("SGST");
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 60, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("GSTIN:");
        panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 60, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, 300, 20));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1120, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("reciept no:");
        panel_print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("reciept no:");
        panel_print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Sr.No:");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 60, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("Head:");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 50, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setText("Date:");
        panel_print.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 60, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setText("1");
        panel_print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 60, -1));

        txt_coursrName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_coursrName.setText("1");
        panel_print.add(txt_coursrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 60, -1));

        txt_cgst1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_cgst1.setText("CGST(9%)");
        panel_print.add(txt_cgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 80, 20));

        txt_sgst2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_sgst2.setText("SGST(8%)");
        panel_print.add(txt_sgst2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 70, -1));

        txt_intialAmount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_intialAmount.setText("CGST");
        panel_print.add(txt_intialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 60, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel29.setText("Recevier Signature");
        panel_print.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 150, -1));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1120, 20));

        txt_cgst.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_cgst.setText("CGST");
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 60, -1));

        txt_total.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_total.setText("TOTAL");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 60, -1));

        txt_remarks.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_remarks.setText("Remarks:");
        panel_print.add(txt_remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 170, 30));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 300, 10));

        txt_totalInwords.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_totalInwords.setText("Total in Words:");
        panel_print.add(txt_totalInwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 410, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel34.setText("Total in Words:");
        panel_print.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 120, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel35.setText("Remarks:");
        panel_print.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 70, -1));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 960, 720));

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 36)); // NOI18N
        jLabel4.setText("Print Reciept");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 220, 60));

        setSize(new java.awt.Dimension(1977, 1100));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr=new Color(0,103,103);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        Color clr=new Color(0,153,153);
        panelSearch.setBackground(clr);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        Color clr=new Color(0,103,103);
        panelSearch.setBackground(clr);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnEditCoursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseEntered
        Color clr=new Color(0,153,153);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseEntered

    private void btnEditCoursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCoursesMouseExited
        Color clr=new Color(0,103,103);
        panelEditCourses.setBackground(clr);
    }//GEN-LAST:event_btnEditCoursesMouseExited

    private void btnCourseListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseEntered
        Color clr=new Color(0,153,153);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseEntered

    private void btnCourseListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseListMouseExited
        Color clr=new Color(0,103,103);
        panelCourseList.setBackground(clr);
    }//GEN-LAST:event_btnCourseListMouseExited

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        Color clr=new Color(0,153,153);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void btnViewAllRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseExited
        Color clr=new Color(0,103,103);
        panelViewAllRecord.setBackground(clr);
    }//GEN-LAST:event_btnViewAllRecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        Color clr=new Color(0,153,153);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        Color clr=new Color(0,103,103);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        Color clr=new Color(0,153,153);
        panelLogOut.setBackground(clr);
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        Color clr=new Color(0,103,103);
        panelLogOut.setBackground(clr);
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        Color clr=new Color(0,153,153);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        Color clr=new Color(0,103,103);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        Color clr=new Color(0,153,153);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        Color clr=new Color(0,103,103);
        panelEdit.setBackground(clr);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        UpdateFeeDetails update= new UpdateFeeDetails();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnCourseList;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnEditCourses;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_chequeId;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelCourseList;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelEditCourses;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogOut;
    private javax.swing.JPanel panelPrint;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelViewAllRecord;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cgst1;
    private javax.swing.JLabel txt_chequeId;
    private javax.swing.JLabel txt_coursrName;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_intialAmount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_receviedName;
    private javax.swing.JLabel txt_recieptNo;
    private javax.swing.JLabel txt_remarks;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_sgst2;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalInwords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
